/*
 * Copyright (C) 2021  Cory J. Reid
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package com.coryjreid.modpacksuite.publisher.json;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.google.common.collect.ImmutableList;

import jdk.nashorn.internal.ir.annotations.Immutable;

/**
 * Represents a minecraftinstance.json file which is typically generated by the Twitch Launcher or CurseForge Launcher.
 */
@Immutable
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonDeserialize(using = MinecraftInstanceDeserializer.class)
public class MinecraftInstance {
    private final String mForgeVersion;
    private final String mMinecraftVersion;
    private final List<Addon> mAddons;

    @JsonCreator
    public MinecraftInstance(
        @JsonProperty("forgeVersion") final String forgeVersion,
        @JsonProperty("minecraftVersion") final String minecraftVersion,
        @JsonProperty("addons") final List<Addon> addons) {

        mForgeVersion = forgeVersion;
        mMinecraftVersion = minecraftVersion;
        mAddons = addons;
    }

    public String getForgeVersion() {
        return mForgeVersion;
    }

    public String getMinecraftVersion() {
        return mMinecraftVersion;
    }

    public List<Addon> getAddons() {
        return ImmutableList.copyOf(mAddons);
    }
}
